# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-18 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_display',
            options={},
        ),
    ]
